- name: yumがupdate済であること
  yum:
    name: '*'
    state: latest
    update_cache: yes

# Apache
- name: httpdがインストールされていること
  yum:
    name: httpd24
    state: present

- name: Apacheが起動してenableになっていること
  service:
    name: httpd
    state: started
    enabled: yes

- name: Prefork MPMが有効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^#(LoadModule mpm_prefork_module.*)$'
    line: '\1'
  notify: restart httpd

- name: Worker MPMが無効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^(LoadModule mpm_worker_module.*)$'
    line: '#\1'
  notify: restart httpd

- name: Event MPMが無効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^(LoadModule mpm_event_module.*)$'
    line: '#\1'
  notify: restart httpd

- name: DocumentRootが設定されていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: DocumentRoot "/var/www/html"
    replace: DocumentRoot "{{ document_root }}"
  notify: restart httpd

- name: DocumentRootのディレクトリ設定がされていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: <Directory "/var/www/html">
    replace: <Directory "{{ document_root }}">
  notify: restart httpd

- name: .htaccessが有効になっていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  notify: restart httpd

# PHP
- name: PHPとPHP関連モジュールがインストールされていること
  yum:
    name:
      - php71
      - php71-mysqlnd
      - php71-mbstring
      - php71-pdo
      - php71-bcmath
    state: present
  notify: restart httpd

# mysql
- name: MySQLがインストールされていること
  yum:
    name: mysql
    state: present

# タイムゾーン設定
- name: timezoneが「Asia/Tokyo」となっていること
  timezone:
    name: Asia/Tokyo

# コンポーザー
# TODO:warningの解消（URL指定のせい？現状インストールは成功するので後回し）
- name: composerがインストールされていること
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer
    creates=/usr/bin/composer

- include: local.yml
  when: not is_production

- include: production.yml
  when: is_production