# Apache
- name: httpdがインストールされていること
  yum:
    name: httpd24
    state: present

- name: Apacheが起動してenableになっていること
  service:
    name: httpd
    state: started
    enabled: yes

- name: Prefork MPMが有効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^#(LoadModule mpm_prefork_module.*)$'
    line: '\1'
  notify: restart httpd

- name: Worker MPMが無効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^(LoadModule mpm_worker_module.*)$'
    line: '#\1'
  notify: restart httpd

- name: Event MPMが無効になっていること
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    state: present
    backrefs: yes
    regexp: '^(LoadModule mpm_event_module.*)$'
    line: '#\1'
  notify: restart httpd

- name: DocumentRootが/vagrant/publicになっていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: 'DocumentRoot "/var/www/html"'
    replace: 'DocumentRoot "/vagrant/public"'
  notify: restart httpd

- name: /vagranの設定がされていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '<Directory "/var/www">'
    replace: '<Directory "/vagrant">'
  notify: restart httpd

- name: /vagrant/publicの設定がされていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '<Directory "/var/www/html">'
    replace: '<Directory "/vagrant/public">'
  notify: restart httpd

- name: .htaccessが有効になっていること
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  notify: restart httpd

# PHP
- name: PHPとPHP関連モジュールがインストールされていること
  yum:
    name:
      - php71
      - php71-mysqlnd
      - php71-mbstring
      - php71-pdo
      - php71-bcmath
    state: present
  notify: restart httpd

# mysql
- name: MySQLがインストールされていること
  yum:
    name: mysql
    state: present

# タイムゾーン設定
- name: timezoneが「Asia/Tokyo」となっていること
  timezone:
    name: Asia/Tokyo

# コンポーザー
# TODO:warningの解消（URL指定のせい？現状インストールは成功するので後回し）
- name: composerがインストールされていること
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer
    creates=/usr/bin/composer

# laravel関連設定
- name: ストレージフォルダが書き込み可能であること
  file:
    path: "/vagrant/storage"
    state: directory
    recurse: true
    mode: 0777

- name: キャッシュフォルダが書き込み可能であること
  file:
    path: "/vagrant/bootstrap/cache"
    state: directory
    recurse: true
    mode: 0777