- name: "ルートディレクトリ作成"
  file:
    path: "/var/www/study"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775
    state: directory

- name: "sharedフォルダ生成"
  file:
    path: "/var/www/study/shared"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0777
    recurse: true
    state: directory

- name: ".envファイルの設定"
  template:
    src: "../templates/.env.j2"
    dest: "/var/www/study/shared/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664
